### Introduction to Numpy

In [24]:
import pandas as pd
import numpy as np

#### Creating arrays

In [25]:
#creating arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [29]:
x = np.array([1,2,3,5,7,12])
x

array([ 1,  2,  3,  5,  7, 12])

In [30]:
x[2]

np.int64(3)

In [31]:
x[2] = 10
x

array([ 1,  2, 10,  5,  7, 12])

In [33]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [34]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### Multi-dimensional arrays

In [35]:
np.zeros((5,2)) #five rows and two columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
f = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
f[0, 1] #first row, second column

np.int64(2)

In [40]:
f[0, 1] = 20
f

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
f[0] #first row

array([ 1, 20,  3])

In [44]:
f[2] = [1, 1, 1]

In [45]:
f[:, 1] #second column

array([20,  5,  1])

In [47]:
f[:, 2] = [11, 15, 19] #third column
f

array([[ 1, 20, 11],
       [ 4,  5, 15],
       [ 1,  1, 19]])

#### Randomly Generated Arrays

In [51]:
np.random.seed(10) # if we want to make the random numbers reproducible, we set seed.
np.random.rand(5, 2) #5 rows and 2 columns of random numbers between 0 and 1

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [52]:
np.random.seed(10)
np.random.randn(5, 2) #drawing numbers from a normal distribution

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [53]:
np.random.seed(10)
np.random.randint(low = 0, high = 100, size = (5, 2))

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

#### Element-wise Operations

In [63]:
d = np.arange(1, 5)
d

array([1, 2, 3, 4])

In [64]:
d * 100

array([100, 200, 300, 400])

In [65]:
e = (10 + (d *2)) ** 2 / 100
e

array([1.44, 1.96, 2.56, 3.24])

In [66]:
e + d

array([2.44, 3.96, 5.56, 7.24])

#### Comparison Operations

In [68]:
d >= 2

array([False,  True,  True,  True])

In [69]:
d > e

array([False,  True,  True,  True])

In [71]:
d[d > e]

array([2, 3, 4])

#### Summarizing Operations

In [72]:
d.max()

np.int64(4)

In [73]:
d.mean()

np.float64(2.5)

In [74]:
d.std()

np.float64(1.118033988749895)

In [75]:
d.sum()

np.int64(10)